version: "3"
includes:
  platform:
    taskfile: src/platform/Taskfile.yml
    dir: ./src/platform
  stack:
    taskfile: stack/Taskfile.yml
    dir: ./stack
  web:
    taskfile: src/web/Taskfile.yml
    dir: ./src/web
