version: "3"
tasks:
  add-migration:
    cmds:
      - dotnet ef migrations add {{.CLI_ARGS}} --project Aspen.Data.Database

  migrate:
    cmds:
      - dotnet ef database update --project Aspen.Data.Database
